### ISSUE TITLE
do not stop when a "MySQL has gone away" error pops

### ISSUE THREAD

**Issue by ninsuo** [redcall-io/app#294] opened 2020-05-09 19:49 UTC
Integrate the https://github.com/facile-it/doctrine-mysql-come-back library in RedCall.

It should be as easy as adding the library and the following configuration:

```
                wrapper_class: 'Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Connections\MasterSlaveConnection'
                driver_class: 'Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Driver\PDOMySql\Driver'
                options:
                    x_reconnect_attempts: 3
```

_edit_: looks not working on GCP, should investigate why.

![Screenshot 2020-05-10 at 19 22 28](https://user-images.githubusercontent.com/4152132/81505993-b7685e00-92f3-11ea-95cd-ec8b94342f62.png)

**Comment by dev-mansonthomas** [comment] 2020-06-04 22:01
test last two parameter of this screenshot to avoid "MySQL Server has gone away"

![image](https://user-images.githubusercontent.com/5695269/83814981-9d862500-a6bf-11ea-824d-29e6d827bc36.png)

**Comment by dev-mansonthomas** [comment] 2020-07-03 21:00
wait_timeout=60
max_allowed_packet=256000

set in dev & prod as of 3rd of July

**Comment by dev-mansonthomas** [comment] 2020-07-03 22:12
It doesn't seem to improve the issue.

However, I found that another project based on Symfony implemented a periodic query to DB.

Either set the connection as persistent
if (true === $this->pdo->getAttribute(\PDO::ATTR_PERSISTENT)) {

or implement the ping

https://github.com/GeniusesOfSymfony/WebSocketBundle/issues/197

https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/3.x/docs/PeriodicSetup.md
https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/3.x/src/Periodic/PdoPeriodicPing.php

**Comment by dev-mansonthomas** [comment] 2020-07-03 22:16
another try with 

![image](https://user-images.githubusercontent.com/5695269/86499440-88b6b300-bd8b-11ea-9567-268e0068248a.png)

set in prod & dev

**Comment by dev-mansonthomas** [comment] 2020-07-03 22:23
Still the same issues

Could this be an issue in the session handling ?

```
Message
Uncaught PHP Exception Doctrine\DBAL\Driver\PDOException: "SQLSTATE[HY000]: General error: 2006 MySQL server has gone away" at /srv/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php line 129
Level
CRITICAL
Env
prod
Platform
fpm-fcgi
Exception
```{
   "class": "Doctrine\\DBAL\\Driver\\PDOException",
   "message": "SQLSTATE[HY000]: General error: 2006 MySQL server has gone away",
   "code": 0,
   "file": "/srv/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:129",
   "trace": [
       "/srv/vendor/symfony/http-foundation/Session/Storage/Handler/PdoSessionHandler.php:401",
       "/srv/vendor/symfony/http-foundation/Session/Storage/Proxy/SessionHandlerProxy.php:51",
       "/srv/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php:268",
       "/srv/vendor/symfony/http-foundation/Session/Session.php:189",
       "/srv/vendor/symfony/http-kernel/EventListener/AbstractSessionListener.php:121",
       "/srv/vendor/symfony/event-dispatcher/EventDispatcher.php:304",
       "/srv/vendor/symfony/event-dispatcher/EventDispatcher.php:264",
       "/srv/vendor/symfony/event-dispatcher/EventDispatcher.php:239",
       "/srv/vendor/symfony/event-dispatcher/EventDispatcher.php:73",
       "/srv/vendor/symfony/http-kernel/HttpKernel.php:191",
       "/srv/vendor/symfony/http-kernel/HttpKernel.php:179",
       "/srv/vendor/symfony/http-kernel/HttpKernel.php:80",
       "/srv/vendor/symfony/http-kernel/Kernel.php:201",
       "/srv/public/index.php:46"
   ],
   "previous": {
       "class": "PDOException",
       "message": "SQLSTATE[HY000]: General error: 2006 MySQL server has gone away",
       "code": 0,
       "file": "/srv/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:127",
       "trace": [
           "/srv/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:127",
           "/srv/vendor/symfony/http-foundation/Session/Storage/Handler/PdoSessionHandler.php:401",
           "/srv/vendor/symfony/http-foundation/Session/Storage/Proxy/SessionHandlerProxy.php:51",
           "/srv/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php:268",
           "/srv/vendor/symfony/http-foundation/Session/Session.php:189",
…
Today at 12:22 AM
```

**Comment by dev-mansonthomas** [comment] 2020-07-03 22:40
Even with increase values compared to default, the error keeps occuring while I'm doing nothing (with a tab open on the page), one message per minute.
After closing the tab, the error keep reproducing once per minute.

Removing flags on both DB for now

**Comment by dev-mansonthomas** [comment] 2020-07-03 22:48
after removing flags, the error still occurs once per minute

**Comment by dev-mansonthomas** [comment] 2020-07-04 07:38
For some reasons, the flags where not removed.
When I stopped the instance this morning, the flags were still there.

the error on the MySQL Serveur side :
(Got a packet bigger than 'max_allowed_packet' bytes)

with a setting of 256'000 which is way less than the default value of 16M

So I removed all flags excepted max_allowed_packet and set it to 32M, which is 33554432 (2^25)(we can use 32M in the google cloud console).

Since then the error does not occurs on a minute frequency.

**Comment by dev-mansonthomas** [comment] 2020-07-09 17:08
the max_allowed_packed improved the situation.
however, there's still some occurence of mysql has gone away but for different reason in the MySQL Logs

I've added the slow query monitoring just to check
![image](https://user-images.githubusercontent.com/5695269/87069407-6bfcfe00-c217-11ea-984b-f508e02b2751.png)


![image](https://user-images.githubusercontent.com/5695269/87069342-55ef3d80-c217-11ea-91c5-0c8a67b59cae.png)


details about this error : 
https://dev.mysql.com/doc/refman/8.0/en/communication-errors.html

other resource : 

https://cloud.google.com/sql/docs/mysql/diagnose-issues

**Comment by dev-mansonthomas** [comment] 2020-07-09 17:11
@ninsuo maybe there's something to check in the code about closing connection ? 

![image](https://user-images.githubusercontent.com/5695269/87069654-de6dde00-c217-11ea-9457-fec0b13c9b56.png)

**Comment by ninsuo** [comment] 2020-10-04 15:40
I successfully installed mysql-come-back on symfony side (had an issue with composer caching on GAE, fixed since a few weeks), it should reduce the number of errors related to MySQL.

**Closed** 2020-10-04 20:22 UTC
Labels: Average, In Progress, Technical Improvements
