### ISSUE TITLE
When the sending is complete, keep the total number of sms sent

### ISSUE THREAD

**Issue by dev-mansonthomas** [redcall-io/app#326] opened 2020-06-11 14:41 UTC
When All sms are sent with success, we can see the green bar with "terminée", can you add the total number of SMS sent, and next to it, the number of response so far with the % it represents.

![image](https://user-images.githubusercontent.com/5695269/84399986-c51a4780-ac01-11ea-9da6-2f2afda6aba7.png)

![image](https://user-images.githubusercontent.com/5695269/84400460-5ab5d700-ac02-11ea-9aff-0e3347979f43.png)

**Comment by ninsuo** [comment] 2020-06-11 14:48
And we should set the bar green once all reachable people have been SMSed, currently, it stays blue, which is wrong.

**Comment by ninsuo** [comment] 2020-06-11 21:26
TODO: when there are unreachable people, add it on the progress bar

**Comment by ninsuo** [comment] 2020-10-04 17:51
duplicate of #166

**Closed by ninsuo** 2020-10-04 17:51 UTC
Labels: Easy, Trigger Status
